###
### Environment
###

# Make the command-line more informational via color
export CLICOLOR=1
export LSCOLORS=Exfxcxdxbxegedabagacad

# Make less work better
export LESS="eFRX"


###
### Paths
###

# Get PATH set up to include local stuff
PATH="${PATH}:$HOME/bin"

# Add Rancher Desktop and nerdctl/kubectl binaries
if [ -d $HOME/.rd/bin ]; then
  PATH="$HOME/.rd/bin:$PATH"
fi


###
### Aliases
###


###
### Load Local-Only (not stored in the repo)
### For things like tokens, etc.
###
if [ -f ~/.zsh.d/zprofile-local ]; then
  source ~/.zsh.d/zprofile-local
fi

###
### Load Host-Only profile
### lets me have Mac- or Linux-specific things
###
if [ -f ~/.zsh.d/zprofile-$(hostname -s) ]; then
  source ~/.zsh.d/zprofile-$(hostname -s)
fi

