###
### Environment
###

# Make the command-line more informational via color
export CLICOLOR=1
export LSCOLORS=Exfxcxdxbxegedabagacad

# Make less work better
LESS="${LESS} --no-init --quit-if-one-screen" && export LESS

export TIMFOO="foo"

###
### Paths
###

# Get PATH set up to include local stuff
PATH="${PATH}:$HOME/bin"

# Add Rancher Desktop and nerdctl/kubectl binaries
if [ -d $HOME/.rd/bin ]; then
  PATH="$HOME/.rd/bin:$PATH"
fi


###
### Aliases
###


###
### Load Local-Only (not stored in the repo)
###
if [ -f ~/.zprofile-local ]; then
  source ~/.zprofile-local
fi
