###
### Environment
###

# Make the command-line more informational via color
export CLICOLOR=1
export LSCOLORS=Exfxcxdxbxegedabagacad

# Make less work better
LESS="${LESS} --no-init --quit-if-one-screen" && export LESS


###
### Paths
###

# Get PATH set up to include local stuff
PATH="${PATH}:$HOME/bin"

# Add python
PATH="${PATH}:$HOME/Library/Python/3.7/bin"

# Add java jdks
PATH="/opt/homebrew/opt/openjdk@17/bin:$PATH"
PATH="/opt/homebrew/opt/openjdk@11/bin:$PATH"


###
### Aliases
###

# alias for htop
alias "htop"="TERM=xterm htop"


###
### Load Local-Only (not stored in the repo)
###
if [ -f "~/.zprofile-local" ]; then
  source ~/.zprofile-local
fi
