# Put homebrew stuff in the path last so it is first
if [[ -f "/opt/homebrew/bin" ]] ; then
  export PATH="/opt/homebrew/bin:$PATH"
fi

# Start tmux if it's not already running, and if we're not in vscode
if [ "vscode" != "$TERM_PROGRAM" ] \
   && [ -z "$TMUX" ] \
   && ! pstree -s $$ | grep -wq code; then
  tmux new-session -A -s main -n local
fi

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.zsh.d/oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Uncomment one of the following lines to change the auto-update behavior
# mode disabled, auto, reminder
zstyle ':omz:update' mode auto

# Uncomment the following line to change how often to auto-update (in days).
zstyle ':omz:update' frequency 13

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# Which plugins would you like to load? (plugins can be found in $ZSH/plugins/*)
# Custom plugins may be added to $ZSH/custom/plugins/
plugins=(
  tmux
  vi-mode
)

# git can be slow
zstyle ':omz:alpha:lib:git' async-prompt force

# this goes before oh-my-zsh.sh is sourced
ZSH_DISABLE_COMPFIX=true

# tmux
#export ZSH_TMUX_AUTOSTART=true
#export ZSH_TMUX_AUTOSTART_ONCE=true
export ZSH_TMUX_AUTOCONNECT=true
export ZSH_TMUX_AUTOQUIT=false
export ZSH_TMUX_ITERM2=false

source $ZSH/oh-my-zsh.sh

# User configuration

setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE

export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

#[[ $TERM == xterm* ]] || : ${PURE_POWER_MODE:=portable}
#source ~/.zsh.d/purepower

# Make kubectl easier tsource <(kubectl completion zsh) 2>&1 > /dev/null
alias "kc"="kubectl"
compdef __start_kubectl kc 2>&1 > /dev/null
export KUBECONFIG=$HOME/.kube/config:$HOME/.kube/rancher-config:$HOME/.kube/aksetest-config:$HOME/.kube/akse1-config

### MANAGED BY RANCHER DESKTOP START (DO NOT EDIT)
export PATH="$HOME/.rd/bin:$PATH"
### MANAGED BY RANCHER DESKTOP END (DO NOT EDIT)

# To customize prompt, run `p10k configure` or edit ~/.zsh.d/p10k.zsh
[[ ! -f ~/.zsh.d/p10k.zsh ]] || source ~/.zsh.d/p10k.zsh


## Tim Stuff

zmodload -i zsh/complist

# Don't use autocd because WTF?
unsetopt autocd

# Fix vi-style search
vi-search-fix() {
  zle vi-cmd-mode
  zle .vi-history-search-backward
}
autoload vi-search-fix
zle -N vi-search-fix
bindkey -M viins '\e/' vi-search-fix
bindkey -M viins '^[/' vi-search-fix

# History should be longer!
HISTSIZE=1000000
SAVEHIST=$HISTSIZE
